version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: '@#dev2021'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      -
volumes:
  mysql_data:
